config/routes.rb
Rails.application.routes.draw do
  root 'secrets#index'
  resources :comments, only: [:new, :create, :destroy]
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :secrets, only: [:index, :show, :new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :secret
  belongs_to :user

  validates :body, length: { minimum: 3}
end

app/models/secret.rb
class Secret < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true
  validates :title, length: { in: 3..50}
  validates :body, length: { minimum: 30}
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :username, length: { in: 3..20}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :secrets, dependent: :destroy
  has_many :comments, dependent: :destroy

  def controversy_points
    all_comments = 0
    self.secrets.each do |secret|
      all_comments += secret.comments.count
    end
    return 0 if all_comments == 0 || self.secrets.count == 0
    all_comments / self.secrets.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.secret, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @comment.secret, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :secret_id, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :set_secret, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /secrets or /secrets.json
  def index
    @secrets = Secret.all.order('created_at DESC')
    @secret = Secret.new
  end

  # GET /secrets/1 or /secrets/1.json
  def show
    @comment = Comment.new(secret: @secret, user: current_user)
  end

  # GET /secrets/new
  def new
    @secret = current_user.secrets.build
  end

  # GET /secrets/1/edit
  def edit
  end

  # POST /secrets or /secrets.json
  def create
    @secrets = Secret.all.order('created_at DESC')
    @secret = current_user.secrets.build(secret_params)

    respond_to do |format|
      if @secret.save
        format.html { redirect_to root_path, notice: "Secret was successfully created." }
        format.json { render :show, status: :created, location: @secret }
      else
        # flash[:alert]=@secret.errors
        format.html { render 'index', status: :unprocessable_entity }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secrets/1 or /secrets/1.json
  def update
    respond_to do |format|
      if @secret.update(secret_params)
        format.html { redirect_to secret_url(@secret), notice: "Secret was successfully updated." }
        format.json { render :show, status: :ok, location: @secret }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secrets/1 or /secrets/1.json
  def destroy
    @secret.destroy

    respond_to do |format|
      format.html { redirect_to secrets_url, notice: "Secret was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_secret
      @secret = Secret.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def secret_params
      params.require(:secret).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :secret_id %>

  <%= form.label :body, "Comment:" %> <br>
  <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret Safe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/5ed27ce724.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class='navbar'>
    <div class='brand'>
      <%= link_to image_tag("safe.png", alt: 'safe', class: 'navbar-logo'), root_path%> <h1><%= link_to 'Secret Safe', root_path %></h1>
    </div>
    <%if !user_signed_in? %>
      <div class="account-buttons">
        <%= button_to "Log In", new_user_session_url, method: "get" %>
        <%= button_to "Sign In", new_user_registration_url, method: "get" %>
      </div>
    <% else %>
      <div class="account-buttons">
        <%= button_to "Log Out", destroy_user_session_url, method: "delete" %>
      </div>
    <% end %>
  </nav>
  <% if alert || notice %>
    <div class="alerts-and-notices">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/secrets/_back_button.html.erb
<div class='back-button'>
      <%= link_to root_path do %>
      <i class="fas fa-times-circle close-icon"></i>
      <% end %>
    </div>

app/views/secrets/_form.html.erb
<%= form_with(model: secret) do |form| %>
  <% if secret.errors.any? %>
    <div class='error' style="color: #E76F51">
      <h2 class='error-header'><%= pluralize(secret.errors.count, "error") %> prohibited this secret from being saved:</h2>

      <ul>
        <% secret.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, 'Description', style: "display: block" %>
    <%= form.text_area :body%>
  </div>

  <div>
    <%= form.submit %>
    <p class="attention">(Attention, you cant delete or edit your secret after submitting.)</p>
  </div>
<% end %>

app/views/secrets/_secret.html.erb
<div id="<%= dom_id secret %>" class="secret">
  <strong>
    <%= secret.title %>
  </strong>
  <% if user_signed_in? && secret.user != nil %>
    <p class="secret-username"><%= secret.user.username %></p>
  <% else %>
    <p class="secret-username">****</p>
  <% end %>
  <p>
    <%= secret.body %>
  </p>

</div>

app/views/secrets/edit.html.erb
<h1>Editing secret</h1>

<%= render "form", secret: @secret %>

<br>

<div>
  <%= link_to "Show this secret", @secret %> |
  <%= link_to "Back to secrets", secrets_path %>
</div>

app/views/secrets/index.html.erb
<head>
  <%= stylesheet_link_tag 'index' %>
</head>
  <% if user_signed_in? %>
    <%= render 'user/profile' %>
  <% else %>
    <div class="placeholder"></div>
  <% end %>
  <div class="secrets-content">
    <% if user_signed_in? %>
      <h2>Tell us your Secret</h2>
      <div class="secret">
        <%= render 'secrets/form', secret: @secret %>
      </div>
    <% end %>
    <h2>Submited Secrets</h2>
    <div id="secrets">
      <% @secrets.each do |secret| %>
        <%= link_to secret, class: 'secret-link' do %>
          <%= render secret %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/secrets/new.html.erb
<h1>New secret</h1>

<%= render "form", secret: @secret %>

<br>

<div>
  <%= link_to "Back to secrets", secrets_path %>
</div>

app/views/secrets/show.html.erb
<%= render 'user/profile' %>

<div class="secret-show">
    <%= render 'back_button' %>

  <div class="show-secret">
    <%= render @secret %>
  </div>
</div>

<div class="comments-wrapper">
  <h2>Comments</h2>
  <div class="comments">
    <div class='comment-form'>
      <%= render 'comments/form', comment: @comment %>
    </div>
  <br>
  <div class="submited-comments">
    <%- @secret.comments.each do |comment|%>
    <div class="comment-first-row">
      <div class="comment-username"><%= comment.user.username %></div>
      <% if current_user == comment.user %>
        <%= button_to comment, method: "delete", class: 'delete-button' do%>
          <i class="fas fa-trash"></i>
        <% end %>
      <% end %>
    </div>
      <div class='comment-body'><%= comment.body %></div>
      <br>
    <% if @secret.comments.index(comment) != @secret.comments.size-1 %>
      <hr>
    <% end %>
    <% end %>
  </div>
 </div>
</div>

app/views/user/_profile.html.erb
  <div>
    <div class="profile">
      <h2>Profile</h2>
      <%= link_to edit_user_registration_path, class: 'edit-profile-link' do %>
        <div class="profile-infos">
        <h3 class='profile-username'><%= current_user.username %></h3>
        <div class='posted-secrets'>
          <strong>Secrets:</strong>
          <%= current_user.secrets.count %>
        </div>
        <div class="posted-comments">
          <strong>Comments:</strong>
          <%= current_user.comments.count %>
        </div>
        <div class="controversy-points">
          <strong>controversy Points:</strong>
          <%= current_user.controversy_points %>
        </div>
        </div>
        <% end %>
    </div>
  </div>